# Generated by Django 2.0.7 on 2018-07-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(to='api.Food'),
        ),
    ]
