# Generated by Django 2.0.7 on 2018-07-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180706_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('id',)},
        ),
    ]
